""" 
    Write a python script that prints "Jay Ganesh..." every 2 seconds. Use the schedule.every(2).seconds.do(...)function.
"""
import schedule
import time

def main():
    print("Jay Ganesh...")

    schedule.every(2).seconds.do(main)

    while True:
        schedule.run_pending()
        time.sleep(1)
            
if __name__ == "__main__":
    main()

"""  
    macbook@192 Assignment_17 % python3 Assignment17_1.py
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
"""